### ISSUE TITLE
Add notification for desktop availability (logon script completion)

### ISSUE THREAD

**Issue by akahn16** [dstaulcu/SystemEventsToSpeech#5]
Once all logon scripts have completed, voice can read windows is ready for use

**Comment by dstaulcu** [comment]
after some testing it appears that there is significant delay in delivery/receipt of event subscriptions near to machine startup and user logon.  system event notifications aren't voiced until over two minutes after desktop is loaded.   need to explore alternate state detection strategy types for system events near to startup/logon.
