### ISSUE TITLE
Add notification for when logon is possible

### ISSUE THREAD

**Issue by dstaulcu** [dstaulcu/SystemEventsToSpeech#9]
![image](https://cloud.githubusercontent.com/assets/6827994/20468604/2bc54472-af66-11e6-973f-f95f60035fbe.png)

**Comment by dstaulcu** [comment]
after some testing it appears that there is significant delay in delivery/receipt of event subscriptions near to machine startup and user logon.  Might need to either defer this to windows 10 or evaluate non-event subscription based methods

**Comment by dstaulcu** [comment]
this could be re-evaluationed in light of use of get-winevent cmdlet as well as forking of code to both user and system components

**Comment by akahn16** [comment]
The code has been forked.
